name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mandazi_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, gd
        coverage: xdebug

    - name: Copy .env
      run: |
        cd mandazi-backend
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: |
        cd mandazi-backend
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: |
        cd mandazi-backend
        php artisan key:generate

    - name: Directory Permissions
      run: |
        cd mandazi-backend
        chmod -R 755 storage bootstrap/cache

    - name: Create Database
      run: |
        cd mandazi-backend
        php artisan migrate --env=testing --force

    - name: Execute tests (Unit and Feature tests)
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: mandazi_test
        DB_USERNAME: root
        DB_PASSWORD: password
      run: |
        cd mandazi-backend
        php artisan test

    - name: Check Code Style
      run: |
        cd mandazi-backend
        ./vendor/bin/phpcs --standard=PSR12 app/